name: Publish

on:
  push:
    tags:
      - v*
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v3
      - name: release
        run: npm publish --access public